# Copyright (c) 2014 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# GNU Makefile based on shared rules provided by the Native Client SDK.
# See README.Makefiles for more details.

VALID_TOOLCHAINS := pnacl newlib

ifeq (,$(NACL_SDK_ROOT))
  $(error NACL_SDK_ROOT is not set.)
endif
include $(NACL_SDK_ROOT)/tools/common.mk

PORTS = zlib
TARGET = zlib
CFLAGS += -Wall
SOURCES = app.cc type.cc handle.cc
LIBS = z ppapi_cpp ppapi

.PHONY: ports
ports:
ifeq (newlib,$(TOOLCHAIN))
	$(MAKE) -C third_party/naclports $(PORTS) NACL_ARCH=i686
	$(MAKE) -C third_party/naclports $(PORTS) NACL_ARCH=x86_64
	$(MAKE) -C third_party/naclports $(PORTS) NACL_ARCH=arm
endif
ifeq (pnacl,$(TOOLCHAIN))
	$(MAKE) -C third_party/naclports $(PORTS) NACL_ARCH=pnacl
endif

# Build rules generated by macros from common.mk:

$(foreach src,$(SOURCES),$(eval $(call COMPILE_RULE,$(src),$(CFLAGS))))

ifeq ($(CONFIG),Release)
$(eval $(call LINK_RULE,$(TARGET)_unstripped,$(SOURCES),$(LIBS),$(DEPS)))
$(eval $(call STRIP_RULE,$(TARGET),$(TARGET)_unstripped))
else
$(eval $(call LINK_RULE,$(TARGET),$(SOURCES),$(LIBS),$(DEPS)))
endif

$(eval $(call NMF_RULE,$(TARGET),))
